version: "3.8"

services:
  postgres:
    container_name: orders-postgres
    image: postgres:latest
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
      POSTGRES_DB: orders_local

  nats:
    container_name: orders-nats-streaming
    image: nats-streaming:latest
    ports:
      - 4222:4222
